### PR TITLE
fix(#166): uses gock networking only for POST requests

### LINKED ISSUE #166: Fix failing metrics test due to rate limit exceeds
Currently, metrics tests are failing due to exceeding rate limit. See https://travis-ci.org/arquillian/ike-prow-plugins/builds/384675732#L819

### PR DESCRIPTION
**Pull request by MatousJobanek**
The gock networking doesn't seem to work correctly when it is enabled for one whole test case. It should be enabled only for the particular request

Fixes #166

### CODE REVIEW

File: pkg/server/metrics_test.go [hunk 1]
```diff
@@ -119,6 +113,16 @@ var _ = Describe("Service Metrics", func() {
...
 })
 
+func setGockMocks() {
+	gock.New("https://api.github.com").
+		Get("/rate_limit").
+		Reply(200).
+		Body(FromFile("../github/client/test_fixtures/gh/low_rate_limit.json"))
+	gock.New("http://127.0.0.1").
+		Post("").
+		EnableNetworking()
```
Comment (dipak-pawar) [inline pkg/server/metrics_test.go]: Don't you think we need to `disableNetworking` after each tests or entire suite?

Comment (MatousJobanek) [reply pkg/server/metrics_test.go]: from the gock's code:
```go
// EnableNetworking enables the use real networking for the current mock.
func (r *Request) EnableNetworking() *Request {
	if r.Response != nil {
		r.Response.UseNetwork = true
	}
	return r
}
```
so I guess that it is tied to the particular request. Then calling the `defer gock.OffAll()` should be enough
